### ISSUE TITLE
[ Feature Request ] Dimmed areas with highlighting

### ISSUE THREAD

**Issue by liaden** [folke/twilight.nvim#10]
I'd love to optionally have syntax highlighting preserved, but muted.

**Comment by folke** [comment]
Initially I made twilight to support this, but unfortunately it doesn't work with floating windows (like I use in `zen-mode`)

There's an upstream issue about this https://github.com/neovim/neovim/issues/14624

If that would get fixed, I could properly support muted colors

**Comment by weilbith** [comment]
I'll install this plugin once this is working. 👍🏾
