### ISSUE TITLE
laggy when using with zenmode

### ISSUE THREAD

**Issue by qvieth** [folke/twilight.nvim#12]
Using twilight outside zenmode works great, while in zenmode it's almost unable  to use (I don't know whether it is it my potato computer's problem, really hope somebody can help because I really like this plugin (also zenmode))

**Comment by qvieth** [comment]
tried move from neovim 0.5 and nvim-treesitter compat branch to neovim nightly and nvimtreesitter master makes issue no longer appear!

**Comment by qvieth** [comment]
I was wrong, disable treesitter fixes the issue, not the update(after reinstallation of neovim and using TSInstall,  twilight becomes laggy again)

**Comment by qvieth** [comment]
So is there an option to use twilight without treesitter (while keep treesitter installed on the system for the other plugins to work) ?

**Comment by folke** [comment]
I just pushed a change where you can now disable treesitter.

Apart from that it would be good to know what kind of lag you experience?

**Comment by qvieth** [comment]
https://user-images.githubusercontent.com/71810726/128475423-13cb3b6a-9ad6-48eb-82f9-c58ad1c34c05.mp4

the extremly one when moving up or down

**Comment by jessevdp** [comment]
I also appear to experience lag when using Twilight in combination with ZenMode.
