### ISSUE TITLE
[Feature request] Highlight current block entirely

### ISSUE THREAD

**Issue by hood** [folke/twilight.nvim#14]
As the title says, it'd be cool to be able to get this plugin to ighlight the whole parent block entirely, instead of highliting the current code block from its start to the current line.

**Comment by folke** [comment]
Would be great if you could post a screenshot of the behavior you would like to see, since it's not entirely clear what you're asking :)

I saw you also posted #13 Is that a duplicate of this one?

**Comment by hood** [comment]
Yep, #13 is a duplicate of this, I posted twice because I had a submission error thrown at me the first time for some reason.

Here a few screenshots showing the behaviour I'd like to see improved:
https://ibb.co/y4JkfB4 <- here only a relative block is highlighted, instead of the entire method I'm in
https://ibb.co/P6qRmnd <- here other methods are being highlighted too, instead of only the one I'm in

**Comment by folke** [comment]
First of all. This is a buffer that has treesitter enabled right?

Of so, then use the treesitter playground plugin to determine what the scope is of the function (it's not function or method, since we already include those)

Once you know the scope, add it in the expand section of the config.

Would also be great to let me know that scope, since it might be useful to add to the default expand scopes.

**Comment by hood** [comment]
This is what I'm seeing using treesitter's playground plugin.

[screenshot](https://i.imgur.com/oLkmbPK.png)

**Comment by folke** [comment]
You'll probably get what you want by adding `method_definition` to the expand section of the config. Does that work?

**Comment by hood** [comment]
@folke Thanks a lot, man. That worked like a charm!

**Comment by vigoux** [comment]
Reviving this issue: do you think you could use the `scope` in tree-sitter locals in order to make the dimming ?
I think that this would help a lot in the clarity, and make the plugin more predictable in some cases ?

**Comment by vigoux** [comment]
It's actually not a really known feature of tree-sitter, but I think you can leverage it 😉
Tell me if I can help in any way, I just started using the plugin, and I really like it so far, great work (again)!
