### ISSUE TITLE
Better Dimming with Markdown Files?

### ISSUE THREAD

**Issue by FOSSilizedDaemon** [folke/twilight.nvim#16]
I am loving using Twilight, but I have noticed that in markdown files Twilight does not proper see the see the beginning or end of each block. For example here you can see it [highlight two blocks](https://imgur.com/5c1HXao.png) instead of just one. Is there anything I can do to get it to only highlight one block?

**Comment by Hubro** [comment]
Have you tried tweaking the `context` config option?

**Comment by FOSSilizedDaemon** [comment]
> Have you tried tweaking the `context` config option?

The issue is sometimes I have more than X lines I need to highlight around the current line.

**Comment by TymekDev** [comment]
I have also experienced a bit awkward dimming in markdown. I have set `context` to 0 and you can see results below.

I found out that using [tree-sitter playground](https://github.com/nvim-treesitter/playground) setting I could provide sensible values to `expand` option in Twilight config. These three values fix make entire paragraph, code block, and list highlighted.
```lua
require("twilight").setup({
  context = 0,
  expand = {
    -- markdown
    "paragraph",
    "fenced_code_block",
    "list",
  }
})
```

I am a bit concerned about possible naming collision in tree-sitter nodes, but I have no clue if it is a valid concern. If it is, then perhaps `expand` could be extended to provide values per filetype?


### Default config with `context = 0`
#### Section and paragraph
<img src="https://user-images.githubusercontent.com/38053499/187191261-cfbb9ba0-4fa5-4a66-8656-1f5e4fcdd236.png" width="30%"> <img src="https://user-images.githubusercontent.com/38053499/187191205-41e01d80-1861-44b9-a18b-aa4e280018f9.png" width="30%"> <img src="https://user-images.githubusercontent.com/38053499/187191222-77e0e0f0-5146-4929-8219-8c3266db9d3c.png" width="30%">

#### Code block
<img src="https://user-images.githubusercontent.com/38053499/187191345-2a88efb3-d3f9-4cbd-9a78-8eba07f0d3fa.png" width="30%"> <img src="https://user-images.githubusercontent.com/38053499/187191363-dfe0ee82-aec1-4e46-b447-6bc0dd1d3dec.png" width="30%"> <img src="https://user-images.githubusercontent.com/38053499/187191374-533d811d-8ac7-4361-9cfe-ef8922171152.png" width="30%">

#### List
<img src="https://user-images.githubusercontent.com/38053499/187191418-06ba1163-a302-4bdf-9f24-a50aa50a959e.png" width="30%"> <img src="https://user-images.githubusercontent.com/38053499/187191432-c07a94e9-b172-4982-97df-e3a0933416db.png" width="30%">
