### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by max397574** [folke/twilight.nvim#2]
I get an error, on startup
![Screen Shot 2021-07-13 at 12 58 33](https://user-images.githubusercontent.com/81827001/125440602-a5ecb107-a981-4413-b92f-ce75dc8d1a2d.png)

[my init.vim](https://github.com/max397574/Vim_Config/blob/master/init.vim)

**Comment by folke** [comment]
Should be fixed now :)

**Comment by max397574** [comment]
so `:PlugUpdate`should do it (vim-plug)?

**Comment by folke** [comment]
I guess so. I'm using Packer.

**Comment by max397574** [comment]
It works without conifguration
but if I add this:
```
lua << EOF
  require("twilight").setup {
    -- your configuration comes here
    -- or leave it empty to use the default settings
    -- refer to the configuration section below
  }
EOF    >>>
```
I get this:

![Screen Shot 2021-07-13 at 13 02 36](https://user-images.githubusercontent.com/81827001/125441109-905e134b-da05-4957-9331-a779fbecaf6b.png)
(line 641 is >>> in the code)

**Comment by folke** [comment]
Damn, should be fine now. I forgot to expose `setup` in `init.lua`

**Comment by max397574** [comment]
works now
