### ISSUE TITLE
[Feature Request]: Second/Additional non-dimmed area that follows the mouse

### ISSUE THREAD

**Issue by joehannes** [folke/twilight.nvim#22]
When working with this plugin on, I find it quite uncomfortable if I am looking for a specific piece of code nearby in the not highlighted areas ...
I'd love for the cursor-area to stay highlighted and the rest to stay dimmed as is right now, but additionally I'd love to see the feature of an additional (optional) highlighted area that doesn't follow the cursor but the mouse.
I guess this would probably not be much work for you and I think it would be super-useful -
you see: I find myself pointing to the area (more or less) where I'm looking for something anyway, so if that highlight would follow the mouse cursor, that would be so awesome. (while the area round the cursor stays highlighted as well - any way)

Imagine for example in a split buffer, you got the cursor in one buffer and quickly want to double check something in one of the other buffers ... need to switch off/toggle the plugin for a sec => oh, but not so, no, you just hover with the mouse that other section in that other buffer and there's the other highlight following that mouse-cursor, yeah!

**Comment by Hubro** [comment]
It sounds like you're requesting a feature that depends on *mouse hover*. This is not possible, as Neovide has no concept of mouse hover or the mouse position in general.
