### ISSUE TITLE
[Feature request] Better document how to customize which text should be visible

### ISSUE THREAD

**Issue by Hubro** [folke/twilight.nvim#24]
I don't understand how Twilight decides which text should be visible, or how to customize it. I use it with Python + Treesitter, and here's an example of how it works:

![image](https://user-images.githubusercontent.com/597206/162817120-09240ba9-1f7e-48b4-8d0d-4cf6c6cfc9b7.png)

I would like it to *always* expand to include the nearest parent function definition, or the nearest parent class definition if I'm not currently inside a function definition.

It sounds like, based on this:

>   expand = { -- for treesitter, we we always try to expand to the top-most ancestor with these types
>    "function",
>    "method",
>    "table",
>    "if_statement",
>  },

That it already should try to include the entire function definition, but it doesn't. It also sounds like based on this:

>   context = 10, -- amount of lines we will try to show around the current line

That it should show at least 10 lines above/below the current line, but it doesn't do that either. In the screenshot, it only shows 1 line above the current line.

I would really love some more in-depth documentation so I can customize which text is visible.

**Comment by Hubro** [comment]
Hey, that works!

Is there currently any way to specify "expand until the closest parent of one of the following types"?

i.e. expand to either a function definition or class definition, whichever is *closer*?

**Comment by JoseConseco** [comment]
It seems there is bug in Twilight config parsing. 
Lets say we setup  expand as so: 
```
expand = {
	"function_definition",
	"method_definition",
	"class_definition",  
}
This will only highlight current function, method or class.  (no if, which, for etc loops) 
```
The problem is Twilight will add its default on top: 
  ```
expand = { -- for treesitter, we we always try to expand to the top-most ancestor with these types
    "function",
    "method",
    "table",
    "if_statement",
  },
```
This makes 'if'  block is always highlighted.  For now I just commented out default expand {} table content in plugin config.lua file itself.
