### ISSUE TITLE
[Feature Request] Always highlight entire function when within the function

### ISSUE THREAD

**Issue by WizardOfFaraz** [folke/twilight.nvim#28]
Great plugin!

Is there a way to always keep the entire function highlighted when within the function?

If yes, is there a way to easily toggle that option without changing my init file and restarting?

**Comment by okuuva** [comment]
I think this is a duplicate of #14 . There's some discussion there how to find the name of the treesitter node to include in the `expand` table using treesitter playground. TL;DR: what you want is most likely to add "method_definition" in the `expand` table.

**Comment by jluzny** [comment]
Adding "function_definition" to the expand section works as expected for Python methods.

**Comment by cmaughan** [comment]
For those coming here trying to make it work with Rust functions, you are looking for 'function_item' in the expand section.....
You're most welcome ;)

**Comment by andrew528i** [comment]
For those who interested for same functionality in **Golang** just add following lines to expand section in your config:
  > function_declaration
  > method_declaration
 
You can also find this out for other languages [here](https://github.com/nvim-treesitter/nvim-treesitter/blob/master/queries/go/highlights.scm). Just change `go` keyword in url to your language and you ready to go!

<img width="1211" alt="image" src="https://github.com/folke/twilight.nvim/assets/26413262/c8b3ec3f-4f2e-4197-82e1-8ebe26c28ae4">
