### ISSUE TITLE
bug: weird highlighting behaviour

### ISSUE THREAD

**Issue by JeanMertz** [folke/twilight.nvim#33]
### Did you check docs and existing issues?

- [X] I have read all the twilight.nvim docs
- [X] I have searched the existing issues of twilight.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

v0.9.0-dev-e30cc8b

### Operating system/version

MacOS 13.2.1

### Describe the bug

Whenever I enable Twilight, this is how my editor looks:

<img width="1020" alt="Screenshot 2023-04-12 at 10 13 42" src="https://user-images.githubusercontent.com/383250/231408086-671b3458-3b6a-45ff-9f48-6328fd6f5180.png">

As you can see, it dims many of the tokens outside of the focus area, but a lot stay as-is.

Here's a list of plugins I'm currently using:

```
  impatient-nvim
  gruvbox-flat-nvim
  which-key-nvim
  lualine-nvim
  nvim-web-devicons
  fidget-nvim
  telescope-nvim
  telescope-zf-native-nvim
  telescope-all-recent
  sqlite-lua
  neoscroll-nvim
  dressing-nvim
  nvim-notify
  gitsigns-nvim
  cmd-palette
  telescope-hop
  zen-mode-nvim
  twilight-nvim
```

It doesn't appear to be a problem with the colorscheme, as switching from `gruvbox-flat` to `gruvbox-material` shows the extract same thing happening (but with different colours, obviously):

<img width="984" alt="Screenshot 2023-04-12 at 11 05 37" src="https://user-images.githubusercontent.com/383250/231409300-cd130722-faab-47de-90b6-d9f5eb2c149f.png">

### Steps To Reproduce

n/a

### Expected Behavior

n/a

### Repro

```Lua
n/a
```

**Comment by jhaux** [comment]
I have the same issue. Any progress @JeanMertz?

**Comment by jhaux** [comment]
Seems like an upgrade to nvim version 0.10 did it for me.

```
NVIM v0.10.0-dev-2284+gf6042d5c3
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
```
