### ISSUE TITLE
feature: disable twilight for certain filetypes

### ISSUE THREAD

**Issue by daUnknownCoder** [folke/twilight.nvim#37]
### Did you check the docs?

- [X] I have read all the twilight.nvim docs

### Is your feature request related to a problem? Please describe.

twilight starts in `Telescope`, `dashboard` which is not intended

### Describe the solution you'd like

an `excluded_filetypes` in twilight config

### Describe alternatives you've considered

none

### Additional context

![image](https://github.com/folke/twilight.nvim/assets/84800625/9c7690c6-8a6c-4d96-ac5d-c0cf11ddd79e)
dashboard ⬆️

**Comment by t184256** [comment]
```
exclude = {}, -- exclude these filetypes
```
