### ISSUE TITLE
Suggestion: integration with nvim-ts-rainbow

### ISSUE THREAD

**Issue by AckslD** [folke/twilight.nvim#4]
Awesome plugin :tada:

Would be great if colored brackets from [nvim-ts-rainbow](https://github.com/p00f/nvim-ts-rainbow) could be disabled in the dimmed regions. At the moment it looks as follows for me:
![image](https://user-images.githubusercontent.com/23341710/125454533-8cb2daed-7096-478b-9cee-ed608de93359.png)

**Comment by folke** [comment]
I just pushed a fix where I set a higher priority for the dimming extmarks. This prevents the rainbow delims to bleed through.
