### ISSUE TITLE
[ Feature Request ] Focus only active window

### ISSUE THREAD

**Issue by Chaitanyabsprip** [folke/twilight.nvim#5]
The plugin should only highlight the context in the current window and dim text in all other windows
 
![Screenshot:2021-07-14_001](https://user-images.githubusercontent.com/55058351/125605415-05b1ca44-3066-481d-ab4e-4cda186a3bea.png)

**Comment by jim-at-jibba** [comment]
I use this plugin with https://github.com/TaDaa/vimade to achieve what you want. and it works well

**Comment by liaden** [comment]
In addition to @jim-at-jibba's suggestion, there is also https://github.com/sunjon/Shade.nvim that works well for this.

**Comment by folke** [comment]
I just pushed an update that implements this. (see the configuration section of the README)

Be aware, that when you have two windows with the same buffer, then this will still hiighlight the current section in both windows.

When windows have different buffers, they will be fully dimmed.
