### ISSUE TITLE
Error on running  twilight

### ISSUE THREAD

**Issue by pulcinello** [folke/twilight.nvim#7]
I really enjoy using zen-mode with this plugin when writing markdown files. But after a recent update, I got the following error:
```
Error detected while processing WinScrolled Autocommands for "*":
E5108: Error executing lua /usr/share/nvim/runtime/lua/vim/treesitter/language.lua:25: no parser for 'markdown' language, see :help treesitter-parsers
```

By the way, I'm running nightly neovim.

**Comment by folke** [comment]
Sorry about that! Just fixed this.
